---
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /var/lib/loki
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:

    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

    - from: 2022-06-30
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
  enable_alertmanager_v2: true
  rule_path: /var/lib/loki/scratch
  storage:
    type: local
    local:
      directory: /var/lib/loki/rules
  # remote_write:
  #   enabled: true
  #   client:
  #     url: http://localhost:9090/api/v1/write

analytics:
  reporting_enabled: false
